name: Build and Deploy Static Site

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          if ! bun install --frozen-lockfile; then
              echo "Lockfile out of sync, updating..."
              bun install
              echo "Please update your lockfile locally and commit it"
              exit 1
          fi

      - name: Type check
        run: bun run type-check

      - name: Lint code
        run: bun run lint

      - name: Run tests
        run: bun test

      - name: Build static site
        run: bun run build

      # Optional: Deploy to GitHub Pages
    #   - name: Deploy to GitHub Pages
    #     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./out
